<<<<<<< HEAD
# Generated by Django 2.2 on 2022-03-24 05:30
=======
# Generated by Django 2.2 on 2022-01-23 12:17
>>>>>>> origin/mediator_features

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Person',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Client ID')),
                ('externalID', models.CharField(max_length=45)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Personal Account',
                'verbose_name_plural': 'Personal Accounts',
                'db_table': 'account_personal',
                'ordering': ('id', 'fullname'),
=======
            name='Patient',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'mediator_patient',
>>>>>>> origin/mediator_features
                'managed': True,
            },
        ),
    ]
