# Generated by Django 2.2 on 2022-03-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mediator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='client_person',
        ),
    ]
