# Generated by Django 2.2 on 2022-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mediator', '0002_auto_20220324_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'managed': True, 'ordering': ('id', 'fullname'), 'verbose_name': 'Client Info', 'verbose_name_plural': 'Client Details'},
        ),
    ]
