# Generated by Django 2.2 on 2022-03-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_mediator', '0002_auto_20220324_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Account',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('accountNo', models.CharField(max_length=45)),
                ('externalID', models.CharField(max_length=45)),
                ('productName', models.CharField(max_length=255)),
                ('officeId', models.CharField(max_length=255)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='group_mediator.Group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Group Account',
                'verbose_name_plural': 'Group Accounts',
                'db_table': 'account_group',
                'managed': True,
            },
        ),
    ]
