# Generated by Django 2.2 on 2022-03-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mediator', '0002_auto_20220324_1818'),
        ('invoice_mediator', '0002_auto_20220324_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_account',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Group AccountID'),
        ),
        migrations.CreateModel(
            name='Personal_Account',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Personal AccountID')),
                ('accountNo', models.CharField(max_length=45)),
                ('externalID', models.CharField(max_length=45)),
                ('productName', models.CharField(max_length=255)),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='patient_mediator.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Personal Account',
                'verbose_name_plural': 'Personal Accounts',
                'db_table': 'account_personal',
                'managed': True,
            },
        ),
    ]
