# Generated by Django 2.2 on 2022-03-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mediator', '0003_auto_20220324_2036'),
        ('invoice_mediator', '0003_auto_20220324_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='InvoiceID')),
                ('invoiceID', models.CharField(max_length=100)),
                ('client_uuid', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('invoice_issuer', models.CharField(max_length=255)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('invoiced_client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='patient_mediator.Person', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'account_invoice',
                'managed': True,
            },
        ),
    ]
