# Generated by Django 2.2 on 2022-03-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_mediator', '0004_billing_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_invoice',
            name='totalGross',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Gross Amount'),
        ),
        migrations.AddField(
            model_name='billing_invoice',
            name='totalNet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Net Amount'),
        ),
    ]
