# Generated by Django 2.2 on 2022-03-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_mediator', '0005_auto_20220324_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_invoice',
            name='invoiced_client',
        ),
        migrations.AlterField(
            model_name='billing_invoice',
            name='invoiceID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
