# Generated by Django 2.2 on 2022-03-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mediator', '0003_auto_20220324_2036'),
        ('invoice_mediator', '0006_auto_20220331_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_invoice',
            name='mifos_clientid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='patient_mediator.Person', verbose_name='Mifos ClientID'),
        ),
    ]
