# Generated by Django 2.2 on 2022-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_mediator', '0007_billing_invoice_mifos_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_invoice',
            name='mifos_clientid',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Mifos ClientID'),
        ),
    ]
