# Generated by Django 2.2 on 2022-03-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Group ID')),
                ('externalID', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=255)),
                ('officeName', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'clients_group',
                'managed': True,
            },
        ),
    ]
