# Generated by Django 2.2 on 2022-02-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainconfigs', '0004_auto_20220202_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='configs',
            name='mediator_port',
            field=models.IntegerField(default=9002, verbose_name='Mediator Port'),
        ),
    ]
