# Generated by Django 2.2 on 2022-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainconfigs', '0005_configs_mediator_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='configs',
            name='openhim_port',
            field=models.IntegerField(default=8080, verbose_name='OpenHIM Port'),
        ),
        migrations.AlterField(
            model_name='configs',
            name='mediator_port',
            field=models.IntegerField(default=443, verbose_name='Mediator Port'),
        ),
    ]
